version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: vendas-api-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vendas_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vendas-api-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: vendas-api-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - vendas-api-network
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: vendas-api-rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - vendas-api-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vendas-api-nestjs
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    networks:
      - vendas-api-network
    volumes:  
      - /app/node_modules  
      - ./src:/app/src    
      - ./crypto-fix.js:/app/crypto-fix.js

networks:
  vendas-api-network:
    name: vendas-api-network
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
